apiVersion: v1
kind: Pod
metadata:
  name: mqtt-client
  namespace: azure-iot-operations
spec:
  containers:
  - args:
    - apk add mosquitto-clients mqttui && sleep infinity
    command:
    - sh
    - -c
    image: alpine
    imagePullPolicy: Always
    name: mqtt-client
    resources:
      limits:
        cpu: 500m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: broker-sat
    - mountPath: /var/run/certs
      name: trust-bundle
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rrdvw
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: vm-iot
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: mqtt-client
  serviceAccountName: mqtt-client
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: broker-sat
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: aio-internal
          expirationSeconds: 86400
          path: broker-sat
  - configMap:
      defaultMode: 420
      name: azure-iot-operations-aio-ca-trust-bundle
    name: trust-bundle
  - name: kube-api-access-rrdvw
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
